m3db/ci-scripts

- test-cover.sh
This adds the ability to override the NPROC when running test coverage.  This is helpful if you are on a system that you want to avoid being pegged by CPU as you run the tests.
cc @prateek @xichen2020 @cw9 @ben-lerner
> Add ability to override NPROC for test-cover

- test-integration.sh
- Set integration test timeout to 10m by default
> Add default integration test timeout 

- test-cover.sh
Right now if unit tests fail, but the "big" tests pass, then the TEST_EXIT variable gets clobbered and the tests will pass when they should have failed
> Fix unit tests passing when they should fail

- common.mk
- metalint.sh
Some linters require the --tests flag to be passed to gometalinter in order to lint tests
> Add --tests flag to gometalinter

- common.mk
cc @prateek 
`gometalinter` released [version 2](https://github.com/alecthomas/gometalinter/releases/tag/v2.0.0) which [promises to contain performance improvements](https://groups.google.com/forum/#!topic/golang-nuts/8XvNgKtUdIY). I've run it on some of our repos so far without issue. The release notes say that most configurations should not need to change and that appears to be the case with us.
Something to note is that they are moving towards releasing binary packages and will be deprecating support for managing linter installation. I'm guessing that means we will need to be responsible for installing the linters we need ourselves, but I don't see that as being a big issue and we can cross that bridge when we come to it.
> [gometalinter] Install version 2.0.0 of gometalinter by default

- test-cover.sh
The first line of coverage output is the `mode: atomic` line which when concatenated together should only appear once at the very top.
> Fix big tests not removing first line of coverage output

- auto-gen.sh
cc @prateek 
We should run mockclean after the vendor path is stripped. Otherwise if the generated mocks uses a *vendored* 3rd party import path, it'll be grouped together alongside the user imports, which is not what we want.
> Rerun mockclean after the vendor path is stripped

- auto-gen.sh
m3cluster no longer uses mock_*.go
@prateek
> Update mock cleanup

- common.mk
- test-big-cover.sh
- test-cover.sh
- test-integration.sh
- include coverage reporting in integration tests
- separate `big` unit tests as a separate make target, include verbose coverage information 
/cc @richardartoul @jeromefroe @xichen2020
> Re-work integration script to include coverage reporting, separate big unit tests

- test-integration.sh
- variables.sh
More details about why can be found here: https://github.com/golang/go/issues/23883
> Do terrible things to make go1.10 coverage reports work

- test-cover.sh
This enables callers from subdirectories to run test-cover.sh
> Take an argument for the ci directory

- common.mk
- variables.sh
Future-proofing ourselves for a world where `GOPATH` isn't a given by 1)
parsing out the path from `go env` and 2) explicitly setting `PATH`
based on that.
> [makefile] always set PATH+GOPATH

- metalint.sh
This modifies the metalinter script to catch a few more edge cases wrt
exit codes.
> [metalint] make output checking more robust

- common.mk
Glide output is useless unless there's an error; this diff follows buildkite's [advice](https://buildkite.com/docs/pipelines/managing-log-output) to collapse the glide output by default.
[Here's](https://buildkite.com/uberopensource/m3/builds/225#05154255-e079-485a-80b0-2a036cecd917) a sample build showing this at work.
> [buildkite] Collapse glide by default

- variables.sh
Currently I get an `Argument list too long` error from any command that is run in a script which sources `variables.sh` in the m3db monorepo. The problem is that `variables.sh` sets an environment variable, `SRC`, which takes up most of the memory that the OS reserves for the environment and arguments when a command is run, resulting in the aforementioned error. `SRC` is set to the output of `find_dirs` which, as best as I can tell, just seeks to return the list of directories which contain Go source code. This commit, therefore, excludes directories within a `node_modules` directory to dramatically reduce the size of `SRC` when run in the m3db monorepo. `node_modules` is managed by `npm` and should be safe to exclude from the `SRC`, `vendor`, which contains Go dependencies, is also …
> Exclude node_modules from output of find_dirs

- gotestcover/LICENSE
- gotestcover/Makefile
- gotestcover/README.md
- gotestcover/gotestcover.go
- gotestcover/gotestcover_test.go
- test-cover.sh
This reverts commit 323f860b6a669b26f8f4e0ca5f3ee5c4f8f6e94d.
I believe this change has been causing corruption in our coverage
reports due to races writing out results. Reverting until we have a
better solution.
> Revert "[cover] deprecate use of gotestcover (#89)"

- test-cover.sh
By default we find packages to test by searching for directories with files
ending in `_test.go`. This misses packages w/o tests that might still be broken,
but might be necessary behavior depending on whether the Go version being called
uses modules. This allows finding packages to test with `go list`. Eventually we
can make this the default behavior when the OSS monorepo is on go modules.
> [test] Allow finding source dirs w/ golist

- docker/build.sh
We may not have permissions in many environments. Specifically, we don't
on new Buildkite hosts.
> [docker] Skip tmp cleanup by default

- test-integration.sh
This will be used by m3db to pass -race for some integration tests to
check for data races.
RACE=true make test-ci-integration-dbnode
> Optionally set -race for integration tests

- common.mk
Tests should panic so we can catch any invariant violations before releasing
> Set PANIC_ON_INVARIANT_VIOLATED=true for all make targets
